.PHONY: all clean scratch zip \
	01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 \
	21 22 23 24 25 26 27 28 28a 29 30 31 32 33 34 35 \
	36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56

all: 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 \
	21 22 23 24 25 26 27 28 28a 29 30 31 32 33 34 35 \
	36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56

01: 01-add-in.txt
	indy -i 01-add-in.txt        -o 01-add-out.txt

02: 02-dbl-in.txt
	indy -i 02-dbl-in.txt        -o 02-dbl-out.txt

03: 03-len-in.txt
	indy -i 03-len-in.txt        -o 03-len-out.txt

04: 04-len-in.txt
	indy -i 04-len-in.txt        -o 04-len-out.txt

05: 05-len+dbl-in.txt
	indy -i 05-len+dbl-in.txt    -o 05-len+dbl-out.txt

06: 06-even-in.txt
	indy -i 06-even-in.txt       -o 06-even-out.txt

07: 07-odd-in.txt
	indy -i 07-odd-in.txt        -o 07-odd-out.txt

08: 08-evenM-in.txt
	indy -i 08-evenM-in.txt      -o 08-evenM-out.txt

09: 09-oddM-in.txt
	indy -i 09-oddM-in.txt       -o 09-oddM-out.txt

10: 10-evenM+half-in.txt
	indy -i 10-evenM+half-in.txt -o 10-evenM+half-out.txt

11: 11-half-in.txt
	indy -i 11-half-in.txt       -o 11-half-out.txt

12: 12-half-in.txt
	indy -i 12-half-in.txt       -o 12-half-out.txt

13: 13-rot+len-in.txt
	indy -i 13-rot+len-in.txt    -o 13-rot+len-out.txt

14: 14-rot+len-in.txt
	indy -i 14-rot+len-in.txt    -o 14-rot+len-out.txt

15: 15-rot+len-in.txt
	indy -i 15-rot+len-in.txt    -o 15-rot+len-out.txt

16: 16-len+rev-in.txt
	indy -i 16-len+rev-in.txt    -o 16-len+rev-out.txt

17: 17-rev-in.txt
	indy -i 17-rev-in.txt        -o 17-rev-out.txt

18: 18-rev-in.txt
	indy -i 18-rev-in.txt        -o 18-rev-out.txt

19: 19-rev-in.txt
	indy -i 19-rev-in.txt        -o 19-rev-out.txt

20: 20-len+rev-in.txt
	indy -i 20-len+rev-in.txt    -o 20-len+rev-out.txt -d lst

21: 21-len+qrev-in.txt
	indy -i 21-len+qrev-in.txt   -o 21-len+qrev-out.txt

22: 22-qrev-in.txt
	indy -i 22-qrev-in.txt       -o 22-qrev-out.txt

23: 23-len+qrev-in.txt
	indy -i 23-len+qrev-in.txt   -o 23-len+qrev-out.txt

24: 24-qrev-in.txt
	indy -i 24-qrev-in.txt       -o 24-qrev-out.txt

25: 25-rev+qrev-in.txt
	indy -i 25-rev+qrev-in.txt   -o 25-rev+qrev-out.txt

26: 26-qrev+rev-in.txt
	indy -i 26-qrev+rev-in.txt   -o 26-qrev+rev-out.txt

27: 27-nth-in.txt
	indy -i 27-nth-in.txt        -o 27-nth-out.txt

28: 28-nth-in.txt
	indy -i 28-nth-in.txt        -o 28-nth-out.txt      -r 25

29: 29-isort-in.txt
	indy -i 29-isort-in.txt      -o 29-isort-out.txt -r 52

30: 30-sorted-in.txt
	indy -i 30-sorted-in.txt     -o 30-sorted-out.txt -d lst -r 265

31: 31-add+mult-in.txt
	indy -i 31-add+mult-in.txt   -o 31-add+mult-out.txt -r 15

32: 32-mult-in.txt
	indy -i 32-mult-in.txt       -o 32-mult-out.txt

33: 33-add-in.txt
	indy -i 33-add-in.txt        -o 33-add-out.txt      -r 25

34: 34-qrev-in.txt
	indy -i 34-qrev-in.txt       -o 34-qrev-out.txt     -r 25

35: 35-subtract-in.txt
	indy -i 35-subtract-in.txt   -o 35-subtract-out.txt

36: 36-len-in.txt
	indy -i 36-len-in.txt        -o 36-len-out.txt

37: 37-oddM-in.txt
	indy -i 37-oddM-in.txt       -o 37-oddM-out.txt

38: 38-nth-in.txt
	indy -i 38-nth-in.txt        -o 38-nth-out.txt

39: 39-assoc-in.txt
	indy -i 39-assoc-in.txt      -o 39-assoc-out.txt

40: 40-comm-add-in.txt
	indy -i 40-comm-add-in.txt   -o 40-comm-add-out.txt

41: 41-comm-add+mult-in.txt
	indy -i 41-comm-add+mult-in.txt -o 41-comm-add+mult-out.txt

42: 42-add-succ-in.txt
	indy -i 42-add-succ-in.txt   -o 42-add-succ-out.txt

43: 43-odd+even-in.txt
	indy -i 43-odd+even-in.txt   -o 43-odd+even-out.txt

44: 44-odd+even-in.txt
	indy -i 44-odd+even-in.txt   -o 44-odd+even-out.txt

45: 45-odd+even-in.txt
	indy -i 45-odd+even-in.txt   -o 45-odd+even-out.txt

46: 46-odd+even-in.txt
	indy -i 46-odd+even-in.txt   -o 46-odd+even-out.txt

47: 47-odd+even-in.txt
	indy -i 47-odd+even-in.txt   -o 47-odd+even-out.txt

48: 48-odd+even-in.txt
	indy -i 48-odd+even-in.txt   -o 48-odd+even-out.txt

49: 49-even-in.txt
	indy -i 49-even-in.txt       -o 49-even-out.txt

50: 50-fact-in.txt
	indy -i 50-fact-in.txt       -o 50-fact-out.txt

51: 51-invariant-in.txt
	indy -i 51-invariant-in.txt  -o 51-invariant-out.txt

52: 52-isort-in.txt
	indy -i 52-isort-in.txt      -o 52-isort-out.txt -d lst -r 250

53: 53-mult-assoc-in.txt
	indy -i 53-mult-assoc-in.txt -o 53-mult-assoc-out.txt -r 50

54: 54-power-in.txt
	indy -i 54-power-in.txt      -o 54-power-out.txt -r 100

55: 55-exercise2.3-in.txt
	indy -i 55-exercise2.3-in.txt -o 55-exercise2.3-out.txt -r 191

56: 56-exercise2.6-in.txt
	indy -i 56-exercise2.6-in.txt -o 56-exercise2.6-out.txt -r 23

clean:
	rm -f *-out.txt
	rm -f check.txt

scratch: clean
	rm -f *~
	rm -f *.zip

zip: all
	check-examples > check.txt
	zip examples.zip *-in.txt *-out.txt check.txt
