.PHONY: all clean scratch zip \
	01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 \
	21 22 23 24 25 26 27 28 28a 29 30 31 32 33 34 35 \
	36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56

all: 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 \
	21 22 23 24 25 26 27 28 28a 29 30 31 32 33 34 35 \
	36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56

01: 01-add-input.txt
	spec -i 01-add-input.txt        -o 01-add-output.txt

02: 02-dbl-input.txt
	spec -i 02-dbl-input.txt        -o 02-dbl-output.txt

03: 03-len-input.txt
	spec -i 03-len-input.txt        -o 03-len-output.txt

04: 04-len-input.txt
	spec -i 04-len-input.txt        -o 04-len-output.txt

05: 05-len+dbl-input.txt
	spec -i 05-len+dbl-input.txt    -o 05-len+dbl-output.txt

06: 06-even-input.txt
	spec -i 06-even-input.txt       -o 06-even-output.txt

07: 07-odd-input.txt
	spec -i 07-odd-input.txt        -o 07-odd-output.txt

08: 08-evenM-input.txt
	spec -i 08-evenM-input.txt      -o 08-evenM-output.txt

09: 09-oddM-input.txt
	spec -i 09-oddM-input.txt       -o 09-oddM-output.txt

10: 10-evenM+half-input.txt
	spec -i 10-evenM+half-input.txt -o 10-evenM+half-output.txt

11: 11-half-input.txt
	spec -i 11-half-input.txt       -o 11-half-output.txt

12: 12-half-input.txt
	spec -i 12-half-input.txt       -o 12-half-output.txt

13: 13-rot+len-input.txt
	spec -i 13-rot+len-input.txt    -o 13-rot+len-output.txt

14: 14-rot+len-input.txt
	spec -i 14-rot+len-input.txt    -o 14-rot+len-output.txt

15: 15-rot+len-input.txt
	spec -i 15-rot+len-input.txt    -o 15-rot+len-output.txt

16: 16-len+rev-input.txt
	spec -i 16-len+rev-input.txt    -o 16-len+rev-output.txt

17: 17-rev-input.txt
	spec -i 17-rev-input.txt        -o 17-rev-output.txt

18: 18-rev-input.txt
	spec -i 18-rev-input.txt        -o 18-rev-output.txt

19: 19-rev-input.txt
	spec -i 19-rev-input.txt        -o 19-rev-output.txt

20: 20-len+rev-input.txt
	spec -i 20-len+rev-input.txt    -o 20-len+rev-output.txt -d lst

21: 21-len+qrev-input.txt
	spec -i 21-len+qrev-input.txt   -o 21-len+qrev-output.txt

22: 22-qrev-input.txt
	spec -i 22-qrev-input.txt       -o 22-qrev-output.txt

23: 23-len+qrev-input.txt
	spec -i 23-len+qrev-input.txt   -o 23-len+qrev-output.txt

24: 24-qrev-input.txt
	spec -i 24-qrev-input.txt       -o 24-qrev-output.txt

25: 25-rev+qrev-input.txt
	spec -i 25-rev+qrev-input.txt   -o 25-rev+qrev-output.txt

26: 26-qrev+rev-input.txt
	spec -i 26-qrev+rev-input.txt   -o 26-qrev+rev-output.txt

27: 27-nth-input.txt
	spec -i 27-nth-input.txt        -o 27-nth-output.txt

28: 28-nth-input.txt
	spec -i 28-nth-input.txt        -o 28-nth-output.txt      -r 25

29: 29-isort-input.txt
	spec -i 29-isort-input.txt      -o 29-isort-output.txt -r 52

30: 30-sorted-input.txt
	spec -i 30-sorted-input.txt     -o 30-sorted-output.txt -d lst -r 265

31: 31-add+mult-input.txt
	spec -i 31-add+mult-input.txt   -o 31-add+mult-output.txt -r 15

32: 32-mult-input.txt
	spec -i 32-mult-input.txt       -o 32-mult-output.txt

33: 33-add-input.txt
	spec -i 33-add-input.txt        -o 33-add-output.txt      -r 25

34: 34-qrev-input.txt
	spec -i 34-qrev-input.txt       -o 34-qrev-output.txt     -r 25

35: 35-subtract-input.txt
	spec -i 35-subtract-input.txt   -o 35-subtract-output.txt

36: 36-len-input.txt
	spec -i 36-len-input.txt        -o 36-len-output.txt

37: 37-oddM-input.txt
	spec -i 37-oddM-input.txt       -o 37-oddM-output.txt

38: 38-nth-input.txt
	spec -i 38-nth-input.txt        -o 38-nth-output.txt

39: 39-assoc-input.txt
	spec -i 39-assoc-input.txt      -o 39-assoc-output.txt

40: 40-comm-add-input.txt
	spec -i 40-comm-add-input.txt   -o 40-comm-add-output.txt

41: 41-comm-add+mult-input.txt
	spec -i 41-comm-add+mult-input.txt -o 41-comm-add+mult-output.txt

42: 42-add-succ-input.txt
	spec -i 42-add-succ-input.txt   -o 42-add-succ-output.txt

43: 43-odd+even-input.txt
	spec -i 43-odd+even-input.txt   -o 43-odd+even-output.txt

44: 44-odd+even-input.txt
	spec -i 44-odd+even-input.txt   -o 44-odd+even-output.txt

45: 45-odd+even-input.txt
	spec -i 45-odd+even-input.txt   -o 45-odd+even-output.txt

46: 46-odd+even-input.txt
	spec -i 46-odd+even-input.txt   -o 46-odd+even-output.txt

47: 47-odd+even-input.txt
	spec -i 47-odd+even-input.txt   -o 47-odd+even-output.txt

48: 48-odd+even-input.txt
	spec -i 48-odd+even-input.txt   -o 48-odd+even-output.txt

49: 49-even-input.txt
	spec -i 49-even-input.txt       -o 49-even-output.txt

50: 50-fact-input.txt
	spec -i 50-fact-input.txt       -o 50-fact-output.txt

51: 51-invariant-input.txt
	spec -i 51-invariant-input.txt  -o 51-invariant-output.txt

52: 52-isort-input.txt
	spec -i 52-isort-input.txt       -o 52-isort-output.txt -d lst -r 250

53: 53-mult-assoc-input.txt
	spec -i 53-mult-assoc-input.txt -o 53-mult-assoc-output.txt -r 50

54: 54-power-input.txt
	spec -i 54-power-input.txt      -o 54-power-output.txt -r 100

55: 55-exercise2.3-input.txt
	spec -i 55-exercise2.3-input.txt -o 55-exercise2.3-output.txt -r 191

56: 56-exercise2.6-input.txt
	spec -i 56-exercise2.6-input.txt -o 56-exercise2.6-output.txt -r 23

clean:
	rm -f *-output.txt
	rm -f check.txt

scratch: clean
	rm -f *~
	rm -f *.zip

zip: all
	check-examples > check.txt
	zip examples.zip *-input.txt *-output.txt check.txt
